### PR TITLE
Text Assembler for boneless (Nearly)

### PR DESCRIPTION
**Pull request by zignig**
Been building a text assembler for Boneless, Not sure if this is heading in the right direction.

Comments , Observations , Flames ?

### CODE REVIEW

**Comment by whitequark** [comment]
Not bad! I like the general direction.

I'm going to take a closer look at the code soon. I feel like the parser could be more structured, but I don't have any concrete implementable suggestions yet.

**Comment by zignig** [comment]
it lives ! , I need a linker.

**Comment by zignig** [comment]
In conversation with @r1901 about simulator integration,  attempting to write and test some assembly. 

Missing  compare immediate (CMPI) and working out the best way to deal with long jumps and how to EXTI in a sane and consistent fashion.

**Comment by zignig** [comment]
This is coming along , I have finally written an ASM program long enough to require long jumps. Time to investigate.

**Comment by zignig** [comment]
I have two TinyFpga BX boards enroute. hooray.

**Comment by zignig** [comment]
Success, A running boneless on tinyFPGAVbx, with blinky.

https://github.com/zignig/tinybx_stuff/tree/master/Boneless

**Comment by zignig** [comment]
Will transfer relevant code.

**Pull request closed without merging**
