### PR TITLE
Boneless Manual Improvements

### PR DESCRIPTION
**Pull request by tpwrules**
This pull request is designed to improve and fix the manual for the Boneless architecture by clarifying and improving the Operation sections, adding material other than the instruction definitions, and ensuring that the manual documents Boneless's behavior as much as possible.

Tasks:
- [x] Define Operation syntax
- [x] Update Operations with new syntax
- [x] Fully document shift/rotate immediate encoding
- [x] Ensure shift/rotate Operation matches Boneless
- [x] Ensure flag generation for arithmetic instructions (in particular C and V) matches Boneless
- [x] Ensure jump conditions match CMP results
- [x] Document all programmer registers and logical variables in Operation
- [x] Categorize instructions incl. table of all the jumps

### CODE REVIEW

**Comment by whitequark** [comment]
Looks good so far!

**Comment by tpwrules** [comment]
Some ideas for renaming the jump instructions.

1: rename `JN` to `NOP`. This gives the ISA a nice, 4 cycle NOP and avoids potential naming conflicts with the proposals below.

2: The various unconditional instructions will not be changed in this proposal. These instructions are `J`, `JAL`, `JR`, `JRAL` (why isn't this JALR though? it's spelled that way in RISC-V and MIPS), `JST`, `JVT`.

3: Prefix all the conditional jumps with `B` instead of `J`. This clearly indicates to the programmer that these instructions depend on the flags and may not always jump.

<opinions based on my personal experience start here, I welcome additional perspectives!>

4: Rename the `S`ign flag to `N`egative. x86 has an `S` flag, but 6502, 68k, and ARM all use `N` and it's more natural to me. This would also change `JS` (jump if sign bit set) to `JN`, separating it from `JSxx` (jump if signed condition).

5: Rename flags-based jumps to `B<flag><Set or Clear>`. This is how 6502, 68k, and ARM spell them and I am more familiar. Also avoids confusion with `N` for negative flag and N for not. Note that x86 spells them the Boneless way.

| From  | To |
| ------------- | ------------- |
| JZ/JNZ, JE/JNE  | BZS/BZC, BEQ/BNE  |
| JS/JNS  | BNS/BNC, BMI/BPL |
| JC/JNC | BCS/BCC |
| JO/JNO | BVS/BVC|

6: Consider renaming signed and unsigned comparisons. I don't really love any of them, but presented below are some different styles for discussion. I like how Boneless keeps the signed and unsigned distinct, but maybe we can assume signed or unsigned by default. I might also like having signed vs. unsigned on the end instead of in the middle, in the vein of MIPS.

Note that the entries are signed/unsigned.

| Condition  | Boneless | x86 | 68k & ARM | New Boneless |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| >= | JSGE/JUGE | jge/jae | BGE/BHS | BGE/BGEU |
| > | JSGT/JUGT | jg/ja | BGT/BHI | BGT/BGTU |
| <= | JSLE/JULE | jle/jbe | BLE/BLS | BLE/BLEU |
| < | JSLT/JULT | jl/jb | BLT/BLO | BLT/BLTU |

**Comment by whitequark** [comment]
All looks good to me!

**Comment by tpwrules** [comment]
That should be the branch instructions updated. I want to add a quick reference chapter and then we should merge this.

**Comment by tpwrules** [comment]
Alright, that's all I wanted to do. Should be ready for merging.

**Comment by whitequark** [comment]
Can you update the spreadsheet too? Also, I think I'll squash the commits, so if you can write a concise summary I can put there that'd be great.

**Comment by whitequark** [comment]
Thanks for the PR, and sorry it's taken so long! I've added you to repository collaborators. Anything we have consensus on, feel free to just commit to master.

**Pull request merged**
