### PR TITLE
directives bikeshed

### PR DESCRIPTION
**Pull request by zignig**
First try.

### CODE REVIEW

**Comment by zignig** [comment]
Not sure how to approach this, I would like to make sure that it is in @whitequark style, but not waste time building dead ends.

Would I be able to get an example asm file with macros  , constants  and _STUFF_ for direction ? 

Purely speculative of course. :)

**Comment by whitequark** [comment]
I'll try to do something like that in the following days.

**Comment by zignig** [comment]
Intent:
1. Directives , have a  series of directives that for performing tasks inside the assembler.

.equ , define a constant symbol (done)
.macro and .endm  , to define a series of instructions that can be invoked by  an instruction (partial)
.include  , prepend another .asm fo the current build,  so libraries can be built.
.section  , create a code section for later linking

2. Encapsulate the Assembler in an object so internal constructs can be interrogated and metadata (symbol maps, entry points, and memory structures) can build built. This is half done, class level variables need to be defined.

2.1 Create linking infrastructure, so the assembler can build a full binary from named and positioned code blocks.

3.0 Pass all existing test scripts.

I think that macro would work as an Instr , so operands and symbols are created and resolved with existing code.   There is some dense python magic going on inside these files.

I will merge my current work onto this branch and you can review at your pleasure.

**Comment by zignig** [comment]
being able to rename registers would be nice.

**Comment by zignig** [comment]
Direction has changed, this patch is no longer germane. 

Will rework for new infrastructure.

**Pull request closed without merging**
